version: '3'
services:
  dynamodb:
    build: .
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    environment:
      - DYNAMODB_DATA_DIR=/home/dynamodblocal/data
      - SHARED_DB=true

volumes:
  dynamodb_data:
