version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=http://host.docker.internal:8000 # url to database
      - region=local # region of database
      - NEED_FAKE_DATA=1 # when 1, will use fake data
